# fly.toml app configuration file generated for patterfrontend-4969 on 2023-08-11T16:06:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patterfrontend-4969"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    VITE_SIGNALLING_HTTP = "https://pattersignalling-9747.fly.dev"
    VITE_SIGNALLING_WS = "wss://pattersignalling-9747.fly.dev"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
