# fly.toml app configuration file generated for pattersignalling-9747 on 2023-08-11T16:07:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pattersignalling-9747"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  FRONTEND_ORIGIN = "https://patter.lol"
  PORT = "8080"
  # METERED_API_KEY is set using `fly secrets`

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
